spring.application.name=detailed-authentication

#DB
spring.datasource.url=jdbc:mysql://localhost:3306/${DB-NAME}?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=${DB_USER_NAME}
spring.datasource.password=${DB_USER_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect


#OAuth2
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_SECRET}
spring.security.oauth2.client.registration.google.scope=

spring.security.oauth2.client.registration.github.client-id=${GITHUB_ID}
spring.security.oauth2.client.registration.github.client-secret=${GITHUB_SECRET}
spring.security.oauth2.client.registration.github.scope=


#JWT Security Configuration details:
jwt.secret=${JWT_SECRET}
jwt.expiration=3600000