spring.application.name=detailed-authentication

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.security.oauth2.client.registration.github.scope=
spring.security.oauth2.client.registration.google.scope=
jwt.secret=